package enums
type RESOURCE_TYPE string
const  (
	DEPLOYMENT= RESOURCE_TYPE("deployment")
	STATEFULSET= RESOURCE_TYPE("statefulset")
	DAEMONSET= RESOURCE_TYPE("daemonset")
	POD= RESOURCE_TYPE("pod")
	REPLICASET= RESOURCE_TYPE("replicaset")
)
type PIPELINE_STATUS string

const  (
	FAILED=PIPELINE_STATUS("FAILED")
	PROCESSING=PIPELINE_STATUS("PROCESSING")
	TERMINATED=PIPELINE_STATUS("TERMINATED")
	WAITING=PIPELINE_STATUS("WAITING")
	TERMINATING=PIPELINE_STATUS("TERMINATING")
	INITIALIZING=PIPELINE_STATUS("INITIALIZING")
	SUCCESSFUL=PIPELINE_STATUS("SUCCESSFUL")
	CANCELLED=PIPELINE_STATUS("CANCELLED")
	ERROR=PIPELINE_STATUS("ERROR")
)
