package enums
type PIPELINE_RESOURCE_TYPE string
const  (
	DEPLOYMENT=PIPELINE_RESOURCE_TYPE("deployment")
	STATEFULSET=PIPELINE_RESOURCE_TYPE("statefulset")
	DAEMONSET=PIPELINE_RESOURCE_TYPE("daemonset")
	POD=PIPELINE_RESOURCE_TYPE("pod")
	REPLICASET=PIPELINE_RESOURCE_TYPE("replicaset")
)
