apiVersion: apps/v1
kind: Deployment
metadata:
  name: klovercloud-ci-agent
  namespace: klovercloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klovercloud-ci-agent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: klovercloud-ci-agent
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app
          imagePullPolicy: Always
          image: klovercloud/ci-agent:v0.1.0
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: klovercloud-ci-agent-envar-config
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livelinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred-dh