definitions:
  common.MetaData:
    properties:
      links:
        items:
          additionalProperties:
            type: string
          type: object
        type: array
      page:
        type: integer
      page_count:
        type: integer
      per_page:
        type: integer
      total_count:
        type: integer
    type: object
  common.ResponseDTO:
    properties:
      _metadata:
        $ref: '#/definitions/common.MetaData'
      data: { }
      message:
        type: string
      status:
        type: string
    type: object
  unstructured.Unstructured:
    properties:
      object:
        additionalProperties: true
        description: |-
          Object is a JSON compatible map with string, float, int, bool, []interface{}, or
          map[string]interface{}
          children.
        type: object
    type: object
  v1.Resource:
    properties:
      descriptors:
        items:
          $ref: '#/definitions/unstructured.Unstructured'
        type: array
      images:
        items:
          type: string
        type: array
      name:
        type: string
      namespace:
        type: string
      process_id:
        type: string
      replica:
        type: integer
      step:
        type: string
      type:
        type: string
    type: object
info:
  contact: { }
  description: agent API
  title: agent API
paths:
  /api/v1/resources/{processId}:
    post:
      description: Apply resources
      parameters:
        - description: Resource Data
          in: body
          name: data
          required: true
          schema:
            $ref: '#/definitions/v1.Resource'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Apply resources
      tags:
        - Resource
swagger: "2.0"
